title: Backend programming
description: "F2M3BAP - Duurzaam Huis"
email: h.braun@ma-web.nl

github_username:  hiddebraun-ma

# Build settings
baseurl: "/F2M3-BAP-Site-2022"
remote_theme: "pmarsceill/just-the-docs"

#plugins:
#  - jekyll-feed

exclude: ["code-examples", "start.sh", ".idea"]
search_enabled: false
heading_anchors: false

# Config theme
# See: https://pmarsceill.github.io/just-the-docs/docs/configuration/
# color_scheme: dark

logo: "/assets/images/logo.png"

bap:
  assignment_url: https://classroom.github.com/a/to-dDHUa
  skip_date_check: false
